### ISSUE TITLE
tau test for e4s 21.02

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest-cori#55]
@wspear @sameershende

We have installed tau in E4S 21.02 as follows:
```
siddiq90@cori02> module load e4s/21.02
siddiq90@cori02> spack find -v tau | tail -n 3

-- cray-cnl7-haswell / intel@19.1.2.254 -------------------------
tau@2.30.1~adios2+binutils~comm~craycnl~cuda+fortran~gasnet+io~level_zero+libdwarf+libelf+libunwind~likwid+mpi~ompt~opari~opencl~openmp+otf2+papi~pdt~phase~ppc64le~profileparam+pthreads~python~rocm~rocprofiler~scorep~shmem~sqlite~x86_64
```

We need a basic smoke test for this package that should a buildspec that should be written in https://github.com/buildtesters/buildtest-cori/tree/devel/buildspecs/e4s which includes: 
- [ ] Use the `e4s` tags so it runs via `buildtest build --tags e4s` in the scheduled pipeline
- [ ] description of test 
- [ ] maintainer for test

The test could be part of `spack test` or E4S Testsuite or a facility specific test. 

We can use `spack load` or `module load` to test the tau instance 

```
siddiq90@cori02> spack load tau
```

or 

```
siddiq90@cori02> module load tau/2.30.1-intel-19.1.2.254
```

So far the taucc wrapper doesn't work which is a known issue.

```
siddiq90@cori02> taucc --version
/bin/sh: /global/cfs/cdirs/m3503/spack-LDvAIlYx/lib/spack/env/cc: No such file or directory
```

We can do basic smoke test for any of the binaries or test specific feature of tau that is worth testing

```
siddiq90@cori02> ls /global/common/software/spackecp/e4s-21.02/software/cray-cnl7-haswell/intel-19.1.2.254/tau-2.30.1-k5sgn5uxdcnqmms7wikx3gxwoe5kfix6/bin/
configure-1.4           ppscript         tau_ebs2otf.pl         tau_pyspark               taucxx
jracy                   pycoolr          tau_ebs_process.pl     tau_python                taudb_configure
jumpshot                pycoolrgui       tau_exec               tau_reduce                taudb_install_cert
opari                   slog2print       tau_f77.sh             tau_resolve_addresses.py  taudb_keygen
otf2profile             tau-config       tau_f90.sh             tau_rewrite               taudb_loadtrial
paraprof                tau2otf          tau_gen_wrapper        tau_selectfile            tauex
perfdmf_configure       tau2otf2         tau_header_replace.pl  tau_show_libs             tauex.multiple
perfdmf_createapp       tau2slog2        tau_java               tau_spark-submit          tauf90
perfdmf_createexp       tau_analyze      tau_javamax.sh         tau_spark_python          tauinc.pl
perfdmf_loadtrial       tau_baseline     tau_load.sh            tau_throttle.sh           tauupc
perfdmfdb.py            tau_caf.sh       tau_macro.sh           tau_trace2json            tcollect10.ini
perfexplorer            tau_cc.sh        tau_merge              tau_treemerge.pl          trace2profile
perfexplorer_configure  tau_coalesce     tau_multimerge         tau_upc.sh
phaseconvert            tau_compiler.sh  tau_pebil_rewrite      tau_user_setup.sh
portal.py               tau_convert      tau_portal.py          taucaf
pprof                   tau_cxx.sh       tau_prof2json.py       taucc
```

**Comment by wspear** [comment]
The NPB3.1 test in the testsuite tests TAU, PDT and PAPI together.  The taucc error is corrected by these pull requests: https://github.com/spack/spack/pull/24457  https://github.com/spack/spack/pull/24456

**Comment by sameershende** [comment]
The taucc error is corrected by these pull requests: [spack/spack#24457](https://github.com/spack/spack/pull/24457) and [spack/spack#24456](https://github.com/spack/spack/pull/24456).

**Comment by shahzebsiddiqui** [comment]
That's good to know. I don't frankly care what gets tested for Tau i will leave that up to either of you. If you need help please read the [CONTRIBUTING.md](https://github.com/buildtesters/buildtest-cori/blob/devel/CONTRIBUTING.md) guide. This could be a test from E4S Testsuite, or a custom test written in buildspec template.

**Comment by wspear** [comment]
A spack test for tau has been added via this PR: https://github.com/spack/spack/pull/25036

**Comment by shahzebsiddiqui** [comment]
Thanks for the update, so given that this is not merged in spack and we have deployments of 20.10, 21.02, 21.05 available on Cori this test won't be available unless spack decides to tell us which PRs we can cherry pick or if they will sync some of these changes to their upstream branches like `e4s-21.02`, `e4s-21.05` branch. In the meantime, we would still need to add test for the facility deployment. Take a look at https://github.com/buildtesters/buildtest-cori/tree/devel/buildspecs/e4s/21.02 if we can run with `spack test` then one of these examples should suffice, if not we would need to write a test in the buildspec format. Please write one for time being. 

We recently deployed `e4s/21.05` so you can see the available instance we have. We also have one in `e4s/21.02` see https://github.com/buildtesters/buildtest-cori/issues/55#issue-927419477

```
siddiq90@cori11> module load e4s
siddiq90@cori11> spack find -v tau
==> In environment e4s
==> Root specs
adios@1.13.1                  gasnet@2021.3.0                mpark-variant@1.4.0               scr@3.0rc1
adios2@2.7.1                  ginkgo@1.3.0                   ninja@1.10.2                      slepc@3.15.0
aml@0.1.0                     globalarrays@5.8               openpmd-api@0.13.4                stc@0.9.0
amrex@21.05                   gmp@6.2.1                      papi@6.0.0.1                      strumpack@5.1.1 ~slate
arborx@1.0                    gotcha@1.0.3                   papyrus@1.0.1                     sundials@5.7.0
argobots@1.1                  hdf5@1.10.7                    parallel-netcdf@1.12.2            superlu@5.2.1
ascent@0.7.1 ~fortran         hypre@2.20.0                   pdt@3.25.1                        superlu-dist@6.4.0
bolt@2.0                      kokkos@3.4.00 +openmp          petsc@3.15.0                      swig@4.0.2
cabana@0.3.0                  kokkos-kernels@3.2.00 +openmp  precice@2.2.1                     swig@4.0.2-fortran
caliper@2.5.0                 legion@21.03.0                 pumi@2.2.5                        sz@2.1.11.1
chai@2.3.0 ~benchmarks~tests  libnrm@0.1.0                   py-libensemble@0.7.2              tasmanian@7.5
conduit@0.7.2                 libquo@1.3.1                   py-petsc4py@3.15.0                tau@2.30.1
darshan-runtime@3.3.0         libunwind@1.5.0                py-warpx@21.05                    turbine@1.3.0
darshan-util@3.3.0            loki@0.1.7                     py-warpx@21.05                    umap@2.1.0
faodel@1.1906.1               mercury@2.0.1                  py-warpx@21.05                    umpire@4.1.2
flecsi@1.4 +cinch             metall@0.13                    qthreads@1.16  scheduler=distrib  upcxx@2021.3.0
flit@2.1.0                    mfem@4.2.0                     raja@0.13.0                       zfp@0.5.5

==> 1 installed package
-- cray-cnl7-haswell / intel@19.1.3.304 -------------------------
tau@2.30.1~adios2+binutils~comm~craycnl~cuda+elf+fortran~gasnet+io~level_zero+libdwarf+libunwind~likwid+mpi~ompt~opari~opencl~openmp+otf2+papi+pdt~phase~ppc64le~profileparam+pthreads~python~rocm~rocprofiler~scorep~shmem~sqlite~x86_64
```

**Comment by wspear** [comment]
Added tau.pdt.papi test to buildtest. Looks like some submit-limit issues are preventing the tests from running as expected within the ci job but they work when launched independently. https://github.com/buildtesters/buildtest-cori/pull/65#event-5177504303

**Comment by shahzebsiddiqui** [comment]
Closing this issue now #65 thanks @wspear
