### ISSUE TITLE
openpmd-api test for E4S 21.02

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest-cori#56]
@ax3l 

We have deployed openpmd-api in E4S/21.02. We need a test for this package 

```
siddiq90@cori02> module load e4s/21.02
siddiq90@cori02> module av openpmd

----------------------- /global/common/software/spackecp/e4s-21.02/modules/cray-cnl7-haswell/ -----------------------
openpmd-api/0.13.2-intel-19.1.2.254
```

We should have a test that test this instance via `module load` or `spack load`

The openpmd-api is built with following variants which enables adios2, hdf5 and mpi. Not sure if its worth testing openpmd-api with these extensions 

```
siddiq90@cori02> spack find -v openpmd-api | tail -n 3

-- cray-cnl7-haswell / intel@19.1.2.254 -------------------------
openpmd-api@0.13.2~adios1+adios2+hdf5~ipo+mpi~python+shared build_type=RelWithDebInfo
```

I notice this package provides the binary `openpmd-ls` the most basic test would be running a `--help` or `--version`.

```
siddiq90@cori02> ls /global/common/software/spackecp/e4s-21.02/software/cray-cnl7-haswell/intel-19.1.2.254/openpmd-api-0.13.2-mw3jnhyf2gxcl7rvozlwyy4gnwf46pg3/bin
openpmd-ls

siddiq90@cori02> openpmd-ls
Usage: openpmd-ls openPMD-series
List information about an openPMD data series.

Options:
    -h, --help    display this help and exit
    -v, --version output version information and exit

Examples:
    openpmd-ls ./samples/git-sample/data%T.h5
    openpmd-ls ./samples/git-sample/data%08T.h5
    openpmd-ls ./samples/serial_write.json
    openpmd-ls ./samples/serial_patch.bp

siddiq90@cori02> openpmd-ls -v
openpmd-ls (openPMD-api) 0.13.2
Copyright 2017-2020 openPMD contributors
Authors: Axel Huebl et al.
License: LGPLv3+
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

So far we don't have a `spack test` for this package so we need a facility test since spack instance can't change for this deployment. 

```
iddiq90@cori02> spack test list 
-- cray-cnl7-haswell / gcc@10.1.0 -------------------------------
6dpakuj hdf5@1.10.7  jketdkj libxml2@2.9.10

-- cray-cnl7-haswell / intel@19.1.2.254 -------------------------
4iabbzw binutils@2.33.1  qfuxp7l libxml2@2.9.10        azazp46 py-toml@0.10.2   uhrnsjh superlu@5.2.1
bz7x543 cmake@3.19.5     bbichdf m4@1.4.18             nn3apq3 python@3.8.8     qx6w4ni umpire@4.1.2
qafehp3 hdf5@1.10.7      ogmvo3b mfem@4.2.0            soru5fu qthreads@1.16    ozp2whr umpire@4.1.2
ngvypfo hypre@2.20.0     r37px5m py-numpy@1.20.1       xjqerqf raja@0.13.0
awsizb4 hypre@2.20.0     7sbv5vq py-pyelftools@0.26    insxzrj sqlite@3.34.0
m3syfqj libsigsegv@2.12  dmd6rax py-setuptools@50.3.2  2jfc7bt strumpack@5.1.1
```

In order to contribute test we need the following

- [ ] a buildspec with test for `openpmd-api` in https://github.com/buildtesters/buildtest-cori/tree/devel/buildspecs/e4s where we store e4s tests
- [x] A brief description of the test
- [x] Maintainer of the test
- [x] Test should have `tags: e4s` in buildspec so it runs via `buildtest build --tags e4s` as part of scheduled pipeline.

Please refer to [CONTRIBUTING.md](https://github.com/buildtesters/buildtest-cori/blob/devel/CONTRIBUTING.md) for more details.

**Comment by ax3l** [comment]
Interesting, I had a spack test variant in if for a long time.
We could just run ctest with it. I'll copy from somewhere, let's see. Maybe the CMake spack package or so

**Comment by ax3l** [comment]
Added tests in https://github.com/spack/spack/pull/25300 :)

**Comment by shahzebsiddiqui** [comment]
Thanks @ax3l so if i understand one of the test is to run `openpmd-ls --version` and the other is running `ctest --output-on-failure -j1` which would run all the tests which could be extensive. For time being, what can we test considering this PR won't get in to your spack instance. We would need test in this repo so we can run the test. Would you be able to provide this.

**Comment by ax3l** [comment]
> and the other is running ctest --output-on-failure -j1 which would run all the tests which could be extensive

That's correct, but I am able to run those tests on public CI with 2 dedicated CPU cores, so they should be easily runnable on any hardware.
